version: '3'
services:
  metricsaggregationplatform:
    image: maven:3.6.3-jdk-8
    build:
     context: .
    volumes:
     - ${PWD}:/tmp/
     - ${PWD}/etc/:/etc/jaggia/
    environment:
     - NUM_THREADS=1
     - SNAPSHOT=1
     - JAVA_OPTS=-Xmx2G -Xms2G
    command: /usr/bin/mvn compile exec:java -Dexec.mainClass=org.cox.map.MetricsAggregator -Dexec.args=\"--inputFile=pom.xml --output=map\" -Pdirect-runner
    restart: unless-stopped
    depends_on:
     - influxdb
#     - kafka

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
     - influxdb-storage:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
     - influxdb
    ports:
     - 3000:3000
    volumes:
     - grafana-storage:/var/lib/grafana

#  elasticsearch:
#      image: elasticsearch:7.9.2
#      container_name: elastic
#      environment:
#        - xpack.security.enabled=false
#        - xpack.monitoring.enabled=false
#        - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      ports:
#        - 9200:9200
#
#  kibana:
#      image: kibana:7.9.2
#      container_name: kibana
#      ports:
#        - 5601:5601
#      environment:
#        - xpack.security.enabled=false
#        - xpack.monitoring.enabled=false
#        - "elasticsearch.url=http://elasticsearch:9200"
#      depends_on:
#        - elasticsearch

volumes:
  grafana-storage:
  influxdb-storage:
